# Supabase Configuration for やさいせんせい

[api]
# API設定
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
# 認証設定
enabled = true
site_url = "com.atsudev.vegetable_teacher://auth/callback"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[auth.email]
# メール認証設定
enable_signup = true
enable_confirmations = false

[storage]
# ストレージ設定（写真保存用）
enabled = true
file_size_limit = 52428800  # 50MB
image_transformation = { enabled = true }

[db]
# データベース設定
port = 54322
major_version = 15